theme: minima
title: My Projects
author: webDevAndres
email: maciasandres02@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog contains a collection of projects and their details

# social links
twitter_webDevAndres: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_webDevAndres:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
